/**
 * Snare drum envelope parameter specifications.
 */

import { DrumParamSpec } from "./types";

export const SNARE_ENVELOPE_SPEC: DrumParamSpec = {
    drum: "snare",
    envelopes: [
        {
            id: "amp",
            label: "AMP",
            mode: "AD",
            params: [
                {
                    id: "attack_ms",
                    label: "Attack",
                    unit: "ms",
                    min: 0,
                    max: 5,
                    step: 0.1,
                    default: 1,
                },
                {
                    id: "decay_ms",
                    label: "Decay",
                    unit: "ms",
                    min: 40,
                    max: 2000,
                    step: 10,
                    default: 320,
                },
                {
                    id: "curve",
                    label: "Curve",
                    unit: "x",
                    min: 0.2,
                    max: 3.0,
                    step: 0.1,
                    default: 1.4,
                    experimental: true,
                },
            ],
        },
        {
            id: "body",
            label: "BODY",
            mode: "AD",
            params: [
                {
                    id: "body_pitch_hz",
                    label: "Body Pitch",
                    unit: "hz",
                    min: 120,
                    max: 400,
                    step: 5,
                    default: 200,
                },
                {
                    id: "body_decay_ms",
                    label: "Body Decay",
                    unit: "ms",
                    min: 30,
                    max: 800,
                    step: 10,
                    default: 180,
                },
                {
                    id: "body_amount_pct",
                    label: "Body Amount",
                    unit: "pct",
                    min: 0,
                    max: 100,
                    step: 1,
                    default: 45,
                },
            ],
        },
        {
            id: "noise",
            label: "NOISE",
            mode: "AD",
            params: [
                {
                    id: "noise_amount_pct",
                    label: "Noise Amount",
                    unit: "pct",
                    min: 0,
                    max: 100,
                    step: 1,
                    default: 55,
                },
                {
                    id: "noise_decay_ms",
                    label: "Noise Decay",
                    unit: "ms",
                    min: 20,
                    max: 2000,
                    step: 10,
                    default: 280,
                },
                {
                    id: "noise_color",
                    label: "Noise Color",
                    unit: "x",
                    min: 0,
                    max: 1,
                    step: 0.01,
                    default: 0.6,
                    experimental: true,
                },
                {
                    id: "noise_band_center_hz",
                    label: "Noise Band Center",
                    unit: "hz",
                    min: 1000,
                    max: 12000,
                    step: 100,
                    default: 5000,
                },
                {
                    id: "noise_band_q",
                    label: "Noise Band Q",
                    unit: "x",
                    min: 0.3,
                    max: 5,
                    step: 0.1,
                    default: 1.2,
                    experimental: true,
                },
            ],
        },
        {
            id: "snap",
            label: "SNAP",
            mode: "AD",
            params: [
                {
                    id: "snap_amount_pct",
                    label: "Snap Amount",
                    unit: "pct",
                    min: 0,
                    max: 100,
                    step: 1,
                    default: 35,
                },
                {
                    id: "snap_decay_ms",
                    label: "Snap Decay",
                    unit: "ms",
                    min: 1,
                    max: 40,
                    step: 1,
                    default: 10,
                },
                {
                    id: "snap_tone_hz",
                    label: "Snap Tone",
                    unit: "hz",
                    min: 1500,
                    max: 12000,
                    step: 100,
                    default: 7000,
                },
            ],
        },
    ],
    macroParams: [
        { id: "tone", label: "Tone (Shell)", unit: "x", min: 0.0, max: 1.0, step: 0.01, default: 0.5 },
        { id: "wire", label: "Wire (Rattle)", unit: "x", min: 0.0, max: 1.0, step: 0.01, default: 0.4 },
        { id: "crack", label: "Crack (Snap)", unit: "x", min: 0.0, max: 1.0, step: 0.01, default: 0.5 },
        { id: "body", label: "Body (Depth)", unit: "x", min: 0.0, max: 1.0, step: 0.01, default: 0.5 },
    ],
};
