/**
 * Kick drum envelope parameter specifications.
 */

import { DrumParamSpec } from "./types";

export const KICK_ENVELOPE_SPEC: DrumParamSpec = {
    drum: "kick",
    envelopes: [
        {
            id: "amp",
            label: "AMP",
            mode: "AHD",
            params: [
                {
                    id: "attack_ms",
                    label: "Attack",
                    unit: "ms",
                    min: 0,
                    max: 10,
                    step: 0.1,
                    default: 1,
                },
                {
                    id: "hold_ms",
                    label: "Hold",
                    unit: "ms",
                    min: 0,
                    max: 30,
                    step: 0.5,
                    default: 5,
                },
                {
                    id: "decay_ms",
                    label: "Decay",
                    unit: "ms",
                    min: 30,
                    max: 2500,
                    step: 10,
                    default: 220,
                },
                {
                    id: "curve",
                    label: "Curve",
                    unit: "x",
                    min: 0.2,
                    max: 3.0,
                    step: 0.1,
                    default: 1.6,
                },
            ],
        },
        {
            id: "pitch",
            label: "PITCH",
            mode: "AD",
            params: [
                {
                    id: "start_pitch_st",
                    label: "Start Pitch",
                    unit: "st",
                    min: 0,
                    max: 48,
                    step: 1,
                    default: 24,
                },
                {
                    id: "pitch_decay_ms",
                    label: "Pitch Decay",
                    unit: "ms",
                    min: 5,
                    max: 250,
                    step: 5,
                    default: 60,
                },
                {
                    id: "pitch_curve",
                    label: "Pitch Curve",
                    unit: "x",
                    min: 0.2,
                    max: 3.0,
                    step: 0.1,
                    default: 1.3,
                },
                {
                    id: "end_pitch_offset_st",
                    label: "End Pitch Offset",
                    unit: "st",
                    min: -12,
                    max: 12,
                    step: 0.5,
                    default: 0,
                },
            ],
        },
        {
            id: "click",
            label: "CLICK",
            mode: "AD",
            params: [
                {
                    id: "click_amount_pct",
                    label: "Click Amount",
                    unit: "pct",
                    min: 0,
                    max: 100,
                    step: 1,
                    default: 35,
                },
                {
                    id: "click_attack_ms",
                    label: "Click Attack",
                    unit: "ms",
                    min: 0,
                    max: 3,
                    step: 0.1,
                    default: 0,
                },
                {
                    id: "click_decay_ms",
                    label: "Click Decay",
                    unit: "ms",
                    min: 1,
                    max: 60,
                    step: 1,
                    default: 12,
                },
                {
                    id: "click_tone_hz",
                    label: "Click Tone",
                    unit: "hz",
                    min: 1000,
                    max: 12000,
                    step: 100,
                    default: 6000,
                },
                {
                    id: "snap",
                    label: "Snap",
                    unit: "x",
                    min: 0,
                    max: 1,
                    step: 0.01,
                    default: 0.5,
                },
            ],
        },
    ],
};
